apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: talos-media-volume
  namespace: servarr
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1500Gi
  storageClassName: nfs-client
  volumeName: pvc-f8ab7f93-1020-49ac-a94c-947b76375781
