apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: talos-media-volume
  namespace: servarr
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1500Gi
  storageClassName: nfs-client
