apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: frigate
    namespace: frigate
spec:
    interval: 1h0m0s
    chart:
        spec:
            chart: frigate
            sourceRef:
                kind: HelmRepository
                name: blakeblackshear
    values:
        envFromSecrets:
        - frigate-rtsp
        
        # -- amount of shared memory to use for caching
        shmSize: 2Gi
        # -- use memory for tmpfs (mounted to /tmp)
        tmpfs:
            enabled: true
            sizeLimit: 2Gi

        nodeSelector:
            topology.kubernetes.io/zone: minipc-0
        tolerations:
        - key: "storage"
          operator: "Equal"
          value: "no-nas"
          effect: "NoSchedule"

        config: |

            auth:
                reset_admin_password: false

            mqtt:
                enabled: False

            tls:
                enabled: False

            objects:
                track:
                - person

            go2rtc:
                streams:
                    lumus1:
                        - "rtsp://admin:{FRIGATE_RTSP_PASSWORD}@lumus1.cctv.fonzdm.xyz:554/h264Preview_01_sub"

                    bullet1:
                        - "rtsp://admin:{FRIGATE_RTSP_PASSWORD}@bullet1.cctv.fonzdm.xyz:554/h264Preview_01_sub"

                    dome1:
                        - "rtsp://admin:{FRIGATE_RTSP_PASSWORD}@dome1.cctv.fonzdm.xyz:554/h264Preview_01_sub"

            cameras:
                lumus1:
                    ffmpeg:
                        inputs:
                        - path: rtsp://127.0.0.1:8554/lumus1
                          roles:
                            - detect

                    detect:
                        width: 640
                        height: 360
                        fps: 5

                    snapshots:
                        enabled: true
                        timestamp: true
                        bounding_box: true
                        retain:
                            default: 3

                bullet1:
                    ffmpeg:
                        inputs:
                        - path: rtsp://127.0.0.1:8554/bullet1
                          roles:
                            - detect

                    detect:
                        width: 640
                        height: 360
                        fps: 5

                    snapshots:
                        enabled: true
                        timestamp: true
                        bounding_box: true
                        retain:
                            default: 3

                dome1:
                    ffmpeg:
                        inputs:
                        - path: rtsp://127.0.0.1:8554/dome1
                          roles:
                            - detect

                    detect:
                        width: 640
                        height: 360
                        fps: 5

                    snapshots:
                        enabled: true
                        timestamp: true
                        bounding_box: true
                        retain:
                            default: 3
