apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: frigate
    namespace: frigate
spec:
    interval: 1h0m0s
    chart:
        spec:
            chart: frigate
            sourceRef:
                kind: HelmRepository
                name: blakeblackshear
    values:
        # -- amount of shared memory to use for caching
        shmSize: 2Gi
        # -- use memory for tmpfs (mounted to /tmp)
        tmpfs:
            enabled: true
            sizeLimit: 2Gi

        nodeSelector:
            topology.kubernetes.io/zone: minipc-0
        tolerations:
        - key: "storage"
          operator: "Equal"
          value: "no-nas"
          effect: "NoSchedule"

        config: |
            auth:
                reset_admin_password: false
            mqtt:
                enabled: False
            tls:
                enabled: False
            cameras:
                dummy_camera:
                    enabled: False
                    ffmpeg:
                        inputs:
                        - path: rtsp://127.0.0.1:554/rtsp
                          roles:
                          - detect
      