apiVersion: v1
kind: Secret
metadata:
    name: frigate-rtsp
    namespace: frigate
type: Opaque
stringData:
    FRIGATE_RTSP_PASSWORD: ENC[AES256_GCM,data:NBEAgTNbiHFQ+irzWE51BQ==,iv:KiD3AAzpQUaO9UVEydAFubf+xIsFM0i9YHb28+YnI4A=,tag:QkmsN8acd7/y7Ib7212dAA==,type:str]
sops:
    age:
        - recipient: age1fcyhrk0yse8cx49cq398z2uaewp3vxzqek5uph0usgsthzvspppqjp7dru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsaHZHYm5Pa0VscmZLdXh4
            djdSV3FxNFk1TjVjREZZUUtTRFJRN3FKc0hJCit3a2RTQmxKS0VEUzJvNWtXWWNY
            M3dmU052NU1PTWsweDVXVlplS0s0SjgKLS0tIE9VMDl4YkxoeVRKbUxVNDFzSVdC
            aVZYVVU0OHpHNWZiSmRXYnh0WHN5bjQKsE5lBZGXEGefMqahN+CYLbljx5YeHIB9
            SVB5wPDYwFtEpIfTVvpzeatL0LVUS6Li5N10QA979v+J6ge0DYX59g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T18:11:39Z"
    mac: ENC[AES256_GCM,data:SPlnZ4FIC6BAFmsQVW9FVvgRrObX+ZvAtYryoVFksgv7oRQZzAYVIib6WM3Od1lLJSZnz9Pqx47sZsks7nA5sNu+XZHlplJz4eEJcuAcHV7yT2vk0ymSLp/QB/j9eto2ey13xhk3Vv1WelX/sCukrfpWVK0WL8ohmXkucDZnbNg=,iv:2byqqfwrMDc52PlxEsNLc72h32bKRmFRud7cmwvVYmQ=,tag:G/w3AEiA+3S9oYn37b3Lxw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
