apiVersion: v1
kind: Secret
metadata:
    name: frigate-rtsp
    namespace: frigate
type: Opaque
stringData:
    RTSP_PASSWORD: ENC[AES256_GCM,data:g/BRngZWCbpGAnmXcSTtmg==,iv:NxzxyAKAzePuNSSqKxwdcHgIun2njsbTHsBNxlsdLCs=,tag:ZGkwvWNQPooxOawYpIGqYQ==,type:str]
sops:
    age:
        - recipient: age1fcyhrk0yse8cx49cq398z2uaewp3vxzqek5uph0usgsthzvspppqjp7dru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvcWxoOEpsc0UwQTdoa3V3
            ZW1yNTl2YzYyaEhtRjNmZlNKOXRQRHkyNTJFCmgvRFFZWnJxZEVDR2MxVVcvMUZu
            MmRBajFKVzNWUW5Dc293UytaeTYvZGsKLS0tIGVzKy9MNFQ4RlpobHZaN0l0KzNm
            a1drYXR4VVhnWFdyQVUvclh0RVpiVXcK/ijIS84JKbmWa5z4cECgpe1XNdv0jorN
            wnM4tQIHGwos0JbT4J/bIXUQ15tvzRvfp8oUMmEhZaucp/SvERy/dQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T15:40:59Z"
    mac: ENC[AES256_GCM,data:kdluUlb7yTbNupCvMy41ICQFj34EpSp19qEu91TuOr+QC17DuEcJlNLX6WchtCsbrOkDfq2pU7iq4WvXJOgOPToaS37J79z+IVHFhxwOVVbO1q0Hx23zkNV/o/k7A6IehA8JHjl/WTRQqBgDSdBdACO35lyEy7cRGM4GjneesbM=,iv:j8L40MQ1q2oi0PS/e0Kazj+R6gLqk5Qz3mDjhrTqOM4=,tag:FQBcZgcO40CLd9pI1a4M9w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
