apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: external-pool 
  namespace: metallb
spec:
   addresses:
   - 192.168.100.0/24
   - 172.16.100.0/24

---

apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: home-external-advertisement
  namespace: metallb
spec:
  ipAddressPools:
  - external-pool
