- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: icloudpd-volume
    persistentVolumeClaim:
      claimName: icloudpd-volume

- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    name: icloudpd-volume
    mountPath: /mnt/icloudpd

