apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloud 
resources:
  - namespace.yaml
  - repository.yaml
  - pvc.yaml
  - icloud-volume.yaml
  - secret.yaml
  - db.yaml
  - release.yaml
  - cloudflare-tunnel.yaml
patches:
  - target:
      kind: Deployment
      labelSelector: "app.kubernetes.io/name=server"
    patch: |-
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: icloudpd-volume
          persistentVolumeClaim:
            claimName: icloudpd-volume
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: icloudpd-volume
          mountPath: /media/icloudpd



