apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloud 
resources:
  - namespace.yaml
  - repository.yaml
  - pvc.yaml
  - icloud-volume.yaml
  - secret.yaml
  - db.yaml
#  - release.yaml
  - cloudflare-tunnel.yaml
