apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloud-storage
  namespace: cloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
  storageClassName: nfs-client

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: icloudpd-volume
  namespace: cloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: nfs-client

