apiVersion: v1
stringData:
    username: immich
    password: ENC[AES256_GCM,data:rOxkqzlR3hS5Keb6YXWcLjVBOiw=,iv:xkdIi96EhOMusZUCDBCT/SfMcq3jZH6+HsnNuC7oduA=,tag:DL01j9N9o+26BFBM0gqbUQ==,type:str]
kind: Secret
metadata:
    name: immich-db-secret
    namespace: cloud
type: kubernetes.io/basic-auth
sops:
    age:
        - recipient: age1fcyhrk0yse8cx49cq398z2uaewp3vxzqek5uph0usgsthzvspppqjp7dru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmcFZBSjA1Z1EvWVMwc2Y1
            RHhuSG8zU3lkUUFHbG5pNzU5c3I1d2Vla3hFCnVpV1BXQUJKektwWis4WHJQREtq
            U0k0VkczTitSTmtzZm9QTERMZXppeUkKLS0tIDF6cFV3c2kxdlVwd2laK09jR2hC
            UFJGYWg1R2JFekJ0ZmE2R3Y3NngxN28KOI577IXx4L/2T8ib7SKxyA4P+654WeYs
            +rhXJsfh+qBrA7aVNiMjeTMCBhtDqy1Xr4MqVn9yc+69GHcZ/vAGig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-28T16:01:14Z"
    mac: ENC[AES256_GCM,data:M47YFbd+1K/0BTVKhf9AD++oinEVm2BdaB5lOIFn+v1bHMoZeYFWi6MQwZ0EY+moZQsFvIvQqlz9IUn4wLYYEGBl1jmN1DXejgW+J691OfRgMVmkev7DzQObWLV1h1R/qHJhLRhpRGVOSheQZEes+jtvbIM6AYv2peLlrayQdsU=,iv:9hBbAEGBd14nMg9qzBDRbafLFrdhpVElixVaauDF8no=,tag:WPf6BDF4QiuVba4Vs2G8PQ==,type:str]
    encrypted_regex: ^(password)$
    version: 3.10.2
