apiVersion: v1
stringData:
    username: ENC[AES256_GCM,data:9bw3HchT,iv:Z6JS2gBKg3Zdf3OMAN3gGJQZrp8YktD3+D9aC4N9syA=,tag:PGOu1JO3Dtg+9wDBNrlk9g==,type:str]
    password: ENC[AES256_GCM,data:Hb+Y2ZMr+HybCElUXF3sBZAOUto=,iv:UZUACq2RIhX9nUm+MFw3x0YEE6T/lOKI+KdNRdRBY4Y=,tag:bNsRj2EfMdiL5kblICfU0g==,type:str]
kind: Secret
metadata:
    name: immich-db-secret
    namespace: cloud
type: kubernetes.io/basic-auth
sops:
    age:
        - recipient: age1fcyhrk0yse8cx49cq398z2uaewp3vxzqek5uph0usgsthzvspppqjp7dru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZjE2L1ZQNzd0eVd6UmVo
            b1lSSU5uSktmNkEwZ1ZFd0RXbjl5Z0ZWQjMwCi9hUFhyWWxwZDhVaDNsMUQ5bzFk
            ZmhsV0pFYUlkOEFQSFErdHJKWDV0V2cKLS0tIFNhRXowTlVlSnhab2JJVkQzWC9x
            SkZLMDlIMEJ6d2wvZGFndkpzSFJOV2cK7PKnMemsJ9QI5upleHhMo7Uz1ZpV/XCz
            i2Z0vheiBVE3SvDc5Jzf8w268XEjOEUPbJeOuDEBltGzpuoEWZFUgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-28T16:09:07Z"
    mac: ENC[AES256_GCM,data:lnN66u4K5JOzMUfT4ZvFT0el9v4/Adnnxu3oylVvd12N2yJyE7t7kec+SRqLWoT5LHXbIXL5lwOUPz1l+sUVhhkSSacxh7x2pGUPvJ6UVqf5JgyzzblYFNTsExNZ34YOmS5mAVMlrTAGwY/G5nyJ87V+tPVBBlOKQicHvMfPcdk=,iv:zXslFnziUcDHBWnzpif0HtJlPtLq04mqoDGOVOmgEmg=,tag:Pd39NZn7Cc/1hJXRKZ9ooQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
