apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flaresolverr 
  namespace: servarr 
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: flaresolverr
      sourceRef:
        kind: HelmRepository
        name: truecharts 
  values:
    operator:
      register: false
      verify:
        enabled: true
        additionalsystem: []
    metrics:
      main:
        enabled: false
    persistence:
      config:
        enabled: true
        type: pvc
        size: 500Mi
        accessModes: ReadWriteMany
        storageClass: nas
        targetSelector:
          main:
            main:
              mountPath: /config
