apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyseerr 
  namespace: servarr 
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: jellyseerr
      sourceRef:
        kind: HelmRepository
        name: truecharts 
  values:
    metrics:
      main:
        enabled: false
    ingress:
      jellyseerr-ing:
        enabled: true
        primary: true
        required: true
        expandObjectName: false
        annotations: {}
        #  cert-manager.io/cluster-issuer: *issuer
        ingressClassName: tailscale
        hosts:
          - host: jellyseerr
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - jellyseerr
        integrations:
          certManager:
            enabled: false
          traefik:
            enabled: false
    persistence:
      config:
        enabled: true
        type: pvc
        size: 500Mi
        accessModes: ReadWriteMany
        storageClass: nas
        targetSelector:
          main:
            main:
              mountPath: /app/config
      media:
        enabled: true
        type: pvc
        existingClaim: talos-media-volume
        targetSelector:
          main:
            main:
              mountPath: /mnt/media

