apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: netbird 
resources:
  - namespace.yaml
  - repository.yaml
  - secret.yaml
  - release-operator.yaml
#  - controller-release.yaml
#  - dashboard-release.yaml
