apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: netbird-conturn
    namespace: netbird
spec:
    interval: 1h0m0s
    chart:
        spec:
            chart: netbird
            sourceRef:
                kind: HelmRepository
                name: netbird-helmrepo 

    postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Service
              labelSelector: "app.kubernetes.io/name=netbird-relay"
            patch: |-
              - op: add
                path: /spec/ports/-
                value:
                  port: 9030
                  targetPort: quic
                  protocol: UDP
                  name: quic
              - op: add
                path: /spec/externalTrafficPolicy
                value:
                 Cluster 
          - target:
              kind: Deployment
              labelSelector: "app.kubernetes.io/name=netbird-relay"
            patch: |-
              - op: add
                path: /spec/template/spec/containers/0/ports/-
                value:
                  containerPort: 9030
                  protocol: UDP
                  name: quic

    values:
      
      management:
        enabled: false 
      
      signal:
        enabled: false

      dashboard:
        enabled: false

      relay:
        enabled: true
        domainName: relay.netbird.service.fonzdm.xyz
        containerPort: 9030
        labels:
          app.kubernetes.io/name: netbird-relay
        affinity:

          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: "app.kubernetes.io/name"
                  operator: In
                  values:
                  - netbird-relay
              topologyKey: "kubernetes.io/hostname"

        service:
          type: LoadBalancer
          port: 9030
          name: http
          annotations: 
            metallb.io/ip-allocated-from-pool: external-pool
            metallb.io/allow-shared-ip: external-pool
            metallb.io/loadBalancerIPs: 192.168.100.20
        envFromSecret:
          NB_AUTH_SECRET: netbird-relay-secret/netbird-relay-secret-key
        env:
          NB_LISTEN_ADDRESS: 0.0.0.0:9030
          NB_RELAY_PATH: /relay
          NB_RELAY_PORT: 9030
          NB_EXPOSED_ADDRESS: rel://relay.netbird.service.fonzdm.xyz:9030/relay
          NB_QUIC_LISTEN_ADDRESS: 0.0.0.0:9030
          NB_LOG_LEVEL: trace
          NB_TLS_CERT_FILE: /tmp/netbird-certs/tls.crt
          NB_TLS_KEY_FILE: /tmp/netbird-certs/tls.key
        volumes:
        - name: relay-netbird-tls
          secret:
            secretName: relay-netbird-tls
        volumeMounts:
        - name: relay-netbird-tls
          readOnly: true
          mountPath: /tmp/netbird-certs
        replicaCount: 4
        ingress:
          enabled: true
          className: "nginx"
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-cloudflare
            
            nginx.ingress.kubernetes.io/secure-backends: "true"
            nginx.ingress.kubernetes.io/proxy-ssl-verify: "false"

            nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
            nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
            nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
            nginx.ingress.kubernetes.io/proxy-buffering: "off"
            nginx.ingress.kubernetes.io/proxy-set-headers: |
              Upgrade $http_upgrade;
              Connection "upgrade";
          hosts:
            - host: relay.netbird.service.fonzdm.xyz
              paths:
                - path: /relay
                  pathType: ImplementationSpecific      
          tls:
          - secretName: relay-netbird-tls
            hosts:
              - relay.netbird.service.fonzdm.xyz
