apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: netbird-conturn
    namespace: netbird
spec:
    interval: 1h0m0s
    chart:
        spec:
            chart: netbird
            sourceRef:
                kind: HelmRepository
                name: netbird-helmrepo 

    postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Service
              labelSelector: "app.kubernetes.io/name=netbird-relay"
            patch: |-
              - op: add
                path: /spec/ports/-
                value:
                  port: 9030
                  targetPort: quic
                  protocol: UDP
                  name: quic
          - target:
              kind: Deployment
              labelSelector: "app.kubernetes.io/name=netbird-relay"
            patch: |-
              - op: add
                path: /spec/template/spec/containers/0/ports/-
                value:
                  port: 9030
                  protocol: UDP
                  name: quic

    values:
      
      management:
        enabled: false 
      
      signal:
        enabled: false

      dashboard:
        enabled: false

      relay:
        enabled: true
        domainName: relay.netbird.service.fonzdm.xyz
        containerPort: 9030
        labels:
          app.kubernetes.io/name: netbird-relay
        service:
          type: LoadBalancer
          port: 9030
          name: http
          annotations: 
            metallb.io/ip-allocated-from-pool: external-pool
            metallb.io/allow-shared-ip: external-pool
            metallb.io/loadBalancerIPs: 192.168.100.20
        envFromSecret:
          NB_AUTH_SECRET: "netbird-relay-secret/relay-secret-key"
        envRaw:
          NB_LISTEN_ADDRESS: 0.0.0.0:9030
          NB_RELAY_PATH: "/relay"
          NB_RELAY_PORT: 9030
          NB_EXPOSED_ADDRESS: rels://relay.netbird.service.fonzdm.xyz:9030/relay
        volumes: []
        volumeMounts: []
        replicaCount: 1
        ingress:
          enabled: true
          className: "nginx"
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-cloudflare
            # kubernetes.io/ingress.class: nginx
            # kubernetes.io/tls-acme: "true"
            # nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
            # nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
          hosts:
            - host: relay.netbird.service.fonzdm.xyz
              paths:
                - path: /relay
                  pathType: ImplementationSpecific      
          tls:
          - secretName: relay-netbird-tls
            hosts:
              - relay.netbird.service.fonzdm.xyz
