apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: netbird-controller 
    namespace: netbird
spec:
    interval: 1h0m0s
    chart:
        spec:
            chart: netbird
            sourceRef:
                kind: HelmRepository
                name: netbird-helmrepo 
    values:
      global:
        namespace: netbird
      
      management:
        ingress:
          enabled: true
          className: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-cloudflare
          hosts:
            - host: management.netbird.service.fonzdm.xyz
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            - secretName: management-netbird-tls
              hosts:
                - management.netbird.service.fonzdm.xyz
      
        persistentVolume:
          enabled: true
          accessModes: [ReadWriteMany]
          size: 10Mi
          storageClass: nfs-client
      
        metrics:
          enabled: true
      
      dashboard:
        ingress:
          enabled: true
          className: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-cloudflare
          hosts:
            - host: dashboard.netbird.service.fonzdm.xyz
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            - secretName: dashboard-netbird-tls
              hosts:
                - dashboard.netbird.service.fonzdm.xyz
      
        service:
          type: ClusterIP
      
        metrics:
          enabled: true
      
        persistentVolume:
          enabled: true
          accessModes: [ReadWriteMany]
          storageClass: nfs-client
      
      signal:
        service:
          type: LoadBalancer
          loadBalancerIP: 192.168.100.1
          annotations:
            metallb.io/ip-allocated-from-pool: external-pool
      
        ingress:
          enabled: true
          className: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-cloudflare
          hosts:
            - host: signal.netbird.service.fonzdm.xyz
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            - secretName: signal-netbird-tls
              hosts:
                - signal.netbird.service.fonzdm.xyz
      
        metrics:
          enabled: true
      
        persistentVolume:
          enabled: true
          accessModes: [ReadWriteMany]
          storageClass: nfs-client
      
      relay:
        service:
          type: LoadBalancer
          loadBalancerIP: 192.168.100.0
          annotations:
            metallb.io/ip-allocated-from-pool: external-pool
      
        env:
          NB_RELAY_EXPOSED_ADDRESS: "192.168.100.0:33080" 
      
        ingress:
          enabled: true
          className: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-cloudflare
          hosts:
            - host: relay.netbird.service.fonzdm.xyz
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            - secretName: relay-netbird-tls
              hosts:
                - relay.netbird.service.fonzdm.xyz
      
        metrics:
          enabled: true
      
        persistentVolume:
          enabled: true
          accessModes: [ReadWriteMany]
          storageClass: nfs-client
      
      metrics:
        serviceMonitor:
          enabled: true
          namespace: netbird
      
