apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-device-keystore-passwords
    namespace: home-assistant
type: Opaque
stringData:
    fonzdm: ENC[AES256_GCM,data:TeinAlEyYT4vp6q0PAXsxETL9pQ2Nmp648Xcw3yLGFDPkGsZuZzudrcZfA0=,iv:45GcFxK6xCZCh+QlVCEmLRgfNmIVtCUuxmNaGQ9EpDE=,tag:fGKV8D0qpTdHFL365CzMBQ==,type:str]
    fraciervo: ENC[AES256_GCM,data:cDB4J58cKeGw5joIgwWvXo40FTBzlB4s2xvhgVdVyBeg0S5cxReGLOxj/3g=,iv:ex2isEDFuY1VgRj1Vzi+1qALbMPCBmOHsdd5SdE/EAo=,tag:G16pa5WTAOM8wspOd+k7oA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2T1RPMzh3WUFsTHgwL0gv
            OUk2NUMrVGoyc0duOTZHWlRBWDBWcnBiV0R3ClkyRHRON2c0T0l5TE5EUVdoclFv
            UFNBNkYxTmpqYUNOSXVpakhrN0F5WHcKLS0tIElGSVRLN1ZQVVR1dGFUVjQxWmtx
            ZUE2NDdNYXA3TXpyOTFVQUdmRkNDUVUKhPopKUnnGKK4Jl5R+818/wcLLq7MMKZu
            bJoywokNwj1gGhC8JbmpxHiYRdeTqyQAP/340qYgN+1nAC31jr9QrQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fcyhrk0yse8cx49cq398z2uaewp3vxzqek5uph0usgsthzvspppqjp7dru
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T22:24:05Z"
    mac: ENC[AES256_GCM,data:Sx8AWOYmEG20Dw4iyXeszwp7Lh2F1C9stNB69X3ptAkWpokMiJxt9hGxz0RLfywjlrsFFMuDzcudvHsN6W58tIgkywHSQAHNc79BjQgYuzb24b8jG1G4QgpocB+OnOIa/6Gh3X0EntFlYTLws7L3JllmWUmYdezMyF9SdRx0cp4=,iv:eQlLeZZPobXU83UhmiUTh66dudX5Yy7ndvAZAxM5Ggk=,tag:/0j2RWq0scebMI9c3WKs2w==,type:str]
    version: 3.13.3
