apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-tunnel-token
    namespace: home-assistant
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:YbzkWnp79/g92KxgL/NvZxPflPnYv9qMDHBdt3fMbOnqjx6xSWEMdDWrk6+B8YDp0NGWAIrmNwiy2CWZEPbdh2U/0yQhbr9YP298mbYAgUnHFL9111SDpxPqpHnf5oe+4GDdrlrsm4N8fr07Q/q+zZ1Lw9I1+CyAnciUxfTjr0xTkUk40GZK3TElCkcK4GIdSvjB3+yCCnQ9tYzFCgZ48UrnIxWdplQlHJdkUC/p/SxpyZEVCOUs9Q==,iv:CJhP8YRQQwJVSt/U+0DWJoOOBJuAaR2AFNYLSBQDAu4=,tag:7NnjIYBxGcjGe85e8VRqqQ==,type:str]
sops:
    age:
        - recipient: age1fcyhrk0yse8cx49cq398z2uaewp3vxzqek5uph0usgsthzvspppqjp7dru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTDVNNmlMc0kxRGlKdFVn
            SkpqZ0Z3YXFLRk54cUY4dTU0cnZKUW92dW00Ck5XTTNCYkJZeEczRHNHVTBQMHdT
            S3QwK0VZRCtOSUV3WEdyZ3VHd1p4N0UKLS0tIHhZdVFmOHQ4USt1SWNkVUNOZHMv
            aEZuSU9UMCtHY1UvTjdNemc1N2t3SDgK5//sHG6WM2m26hgaitf3H4mlDZLRBaMa
            43s1kY/iGlqXnMlW3m+tdEmsq0gXNq6vQQttgkzeCCD47yiJoPo17g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-12T15:47:33Z"
    mac: ENC[AES256_GCM,data:zNZRpBsXviJ0yiGu1mh5pCswvmVf16RGmJ+dn15vAuCxeAv0jxW5XZ5/oTjKslKdBOvlVYFCp61O7l1Ir404OA8aKrRLtnb90Fc+Gkim1cN4CL+wsDkJ85K2AK3TLNPzF3BenKJ3yYbQGAS0Ke6I6NC8k858pSOU3TroC/yI/UA=,iv:Y68GzfaCzheTRCvzTqRxLwTQJQFzmszxqpbM44ELvCI=,tag:SO/8gdC8c5L8UdYWA42xmw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
