apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: talos-media-volume
  namespace: servarr
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2000Gi
  storageClassName: localpv-raid
