
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: icloudpd-volume
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: localpv-raid


