apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloud-storage
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
  storageClassName: localpv-raid

