apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: unifi 
configMapGenerator:
  - name: release-main-values
    files:
    - values.yaml=values.yaml
generatorOptions:
  disableNameSuffixHash: true

resources:
  - namespace.yaml
  - repository.yaml
  - release-mongoless.yaml
  - cloudflare-tunnel.yaml
