apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  dependsOn:
    - name: nas
      namespace: nas
  interval: 30m
  releaseName: monitoring
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      interval: 30m
  targetNamespace: monitoring
  install:
    createNamespace: true
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  values:
    grafana:
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-cloudflare
          #nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.0.0/16
        hosts:
          - grafana.service.fonzdm.xyz
        tls:
          - secretName: grafana-ing-tls
            hosts:
            - grafana.service.fonzdm.xyz
    prometheus:
      prometheusSpec:    
        storageSpec: 
          volumeClaimTemplate:
            spec:
              storageClassName: nas
              accessModes: ["ReadWriteMany"]
              resources:
                requests:
                  storage: 20Gi
