apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflare-operator-system 
resources:
  - namespace.yaml
  - gitrepo.yaml 
  - externalkustomization.yaml
  - cloudflare-secrets.yaml
  - main-tunnel.yaml 
