apiVersion: v1
data:
    visiblekey: ENC[AES256_GCM,data:q671MA+AmAhyvqvGNtcUTA==,iv:rnZk1v7Ap0/VxvXMF+HJeN/VsFnBv65HADfcYIWUuEA=,tag:cCsg7ujCeIod+xAG/HOrmg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: testsops-secret
    namespace: testsops
sops:
    age:
        - recipient: age1fcyhrk0yse8cx49cq398z2uaewp3vxzqek5uph0usgsthzvspppqjp7dru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCSVU5MStBWmtoMGNiOXB4
            RUFLQVZYMEdCdWN3QXRoMy9oZ1FlRWN5c0Z3CkxpZFhHMEFQL3FHRGo2LzFPNFcy
            N1ZQQ3p6L2lSNGNFdXdNNURJWlNrY0EKLS0tIE5LVmRkbmk1anQyWEp1U2xsZ1gv
            b2JBVFppOWptUkllL1NQOXMyVG1LT00K89KxrHmF0II2XJDb1JIVQ2d2Oai5ka2N
            RdtUoDU+6zjnnQP8GO8UrNSaGqOK31l88YiYy1iE+cqE8FUEXW0/eg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-18T14:26:23Z"
    mac: ENC[AES256_GCM,data:qxXnpMTPhDiMb4neSDQNOv/ilfH5k8GorzXKNO+ORRWxq4/fG+7MJ3BtUBr3p4nnc1oqzwUc6n+OFsugMWGUCzNX2Yu0Tvl/UuF3S5D6M+ZG2V5bAnjhU+Q40Pz5Gii3W1cTyWuiB+3nvi4yfSFye7ymE0fyYEbOPR0gXuryyjU=,iv:jDaE/49jKgyIytDZBkRiF5LOd/TT8WdFTACsn2bAb4o=,tag:yDPRCsi0y/TUrkzQqK4Snw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
