apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: netbird-operator
  namespace: netbird
spec:
  interval: 1h0m0s
  url: oci://ghcr.io/netbirdio/helm-charts/netbird-operator
  ref:
    tag: 0.8.0

---

# Retained for the optional, currently disabled netbird-relay HelmRelease.
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: netbird-helmrepo
  namespace: netbird
spec:
  interval: 1h0m0s
  url: https://netbirdio.github.io/helms

