apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: truecharts
  namespace: servarr
spec:
  interval: 1h0m0s
  url: oci://oci.trueforge.org/truecharts
  type: oci

---

#https://jellyfin.github.io/jellyfin-helm

apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jellyfin-charts
  namespace: servarr
spec:
  interval: 1h0m0s
  url: https://jellyfin.github.io/jellyfin-helm


---

apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: qbittorrent-operator
  namespace: servarr
spec:
  interval: 1m0s
  url: https://github.com/fonzdm/qbittorrent-operator.git
  ref:
    branch: main

---

apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: app-template
  namespace: servarr
spec:
  interval: 1h0m0s
  url: oci://ghcr.io/bjw-s-labs/helm/app-template
  type: oci