apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 1h0m0s
  url: https://pkgs.tailscale.com/helmcharts
  type: default

