apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: iperf3
  namespace: pm
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: iperf3
      sourceRef:
        kind: HelmRepository
        name: gradiantcharts
  values:
    global:
      storageClass: nas
    commonAnnotations:
      metallb.universe.tf/address-pool: external-pool
      metallb.universe.tf/allow-shared-ip: external-pool
      metallb.io/ip-allocated-from-pool: external-pool
    service:
      loadBalancerIP: 192.168.100.10
      type: LoadBalancer

