apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bazarr
  namespace: servarr
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: servarr
  values:
    controllers:
      bazarr:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            fsGroup: 65533
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 65533
            runAsNonRoot: true
            runAsUser: 65534
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/bazarr # {"$imagepolicy": "flux-system:bazarr-imagepolicy:name"}
              tag: rolling # {"$imagepolicy": "flux-system:bazarr-imagepolicy:tag"}
              digest: sha256:79fc37491f55c7e24427bcd669bce3df2d7415ca432a47ce9d53cc5988af8411 # {"$imagepolicy": "flux-system:bazarr-imagepolicy:digest"}
            env:
              BAZARR__APP__INSTANCENAME: Sonarr
              BAZARR__AUTH__METHOD: External
              BAZARR__AUTH__REQUIRED: DisabledForLocalAddresses
              BAZARR_LOG__DBENABLED: "False"
              BAZARR__LOG__LEVEL: info
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: false
                spec:
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 20m
                memory: 384Mi
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                - ALL
    service:
      app:
        ports:
          http:
            port: 6767
    persistence:
      media:
        existingClaim: talos-media-volume
      config:
        enabled: true
        size: 8Gi
        storageClass: localpv-raid
        accessMode: ReadWriteOnce
        type: persistentVolumeClaim
      tmpfs:
        type: emptyDir
        globalMounts:
        - path: /tmp
          subPath: tmp
    ingress:
      bazarr:
        enabled: false
    route:
      app:
        enabled: true
        kind: HTTPRoute
        parentRefs:
        - name: traefik-gateway
          namespace: ingress
          sectionName: websecure
        hostnames:
        - "bazarr.media.fonzdm.xyz"
        rules:
        - matches:
          - path:
              type: PathPrefix
              value: /
          backendRefs:
          - name: bazarr
            port: 6767
