apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flaresolverr
  namespace: servarr
spec:
  interval: 30m

  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  upgrade:
    cleanupOnFail: true

  values:

    controllers:
      flaresolverr:
        type: deployment

        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 65533
            fsGroup: 65533
            fsGroupChangePolicy: OnRootMismatch

        containers:
          app:
            image:
              repository: ghcr.io/flaresolverr/flaresolverr
              tag: latest
              pullPolicy: IfNotPresent

            env:
              TZ: Europe/Rome
              LOG_LEVEL: info
              LOG_HTML: "false"
              CAPTCHA_SOLVER: none

            ports:
              - name: http
                containerPort: 8191

            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true

    service:
      app:
        controller: flaresolverr
        ports:
          http:
            port: 8191

    ingress:
      main:
        enabled: false

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 1Gi