apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: lidarr
    namespace: servarr
spec:
    interval: 1h0m0s
    chart:
      spec:
        chart: app-template
        sourceRef:
          kind: HelmRepository
          name: bjw-s
          namespace: servarr
    values:
        controllers:
            lidarr:
                annotations:
                    reloader.stakater.com/auto: "true"
                pod:
                    securityContext:
                        fsGroup: 65533 
                        fsGroupChangePolicy: OnRootMismatch
                        runAsGroup: 65533
                        runAsNonRoot: true
                        runAsUser: 65534
                containers:
                    app:
                        image:
                            repository: ghcr.io/linuxserver-labs/prarr
                            tag: lidarr-plugins
                        env:
                            LIDARR__APP__INSTANCENAME: Lidarr
                            LIDARR__AUTH__APIKEY: ENC[AES256_GCM,data:nvs+K7bhqHMEeRZBLC9vC8EPuwor4OMq74yIY9O/4wRj,iv:0PHzi5Rs0errBLTAEwKPtuKjcZt0irBUEZVT9ONxd+w=,tag:TuokjrgvbXy4tH7nUDYjig==,type:str]
                            LIDARR__AUTH__METHOD: External
                            LIDARR__AUTH__REQUIRED: DisabledForLocalAddresses
                            LIDARR__LOG__DBENABLED: "False"
                            LIDARR__LOG__LEVEL: info
                            LIDARR__SERVER__PORT: 8686
                            LIDARR__UPDATE__BRANCH: develop
                        probes:
                            liveness:
                                enabled: true
                                spec:
                                    periodSeconds: 30
                                    timeoutSeconds: 5
                                    failureThreshold: 5
                            readiness:
                                enabled: true
                                custom: true
                                spec:
                                    httpGet:
                                        path: /ping
                                        port: 8686
                                    periodSeconds: 10
                                    timeoutSeconds: 5
                                    failureThreshold: 5
                            startup:
                                enabled: true
                                spec:
                                    failureThreshold: 30
                                    periodSeconds: 10
                        resources:
                            requests:
                                cpu: 20m
                                memory: 384Mi
                            limits:
                                memory: 2Gi
                        securityContext:
                            allowPrivilegeEscalation: false
                            readOnlyRootFilesystem: true
                            capabilities:
                                drop:
                                    - ALL
        service:
            app:
                ports:
                    http:
                        port: 8686
        persistence:
            media:
                existingClaim: talos-media-volume
            config:
                enabled: true
                size: 8Gi
                storageClass: 'localpv-raid'
                accessMode: ReadWriteOnce
                type: persistentVolumeClaim
            tmpfs:
                type: emptyDir
                globalMounts:
                    - path: /tmp
                      subPath: tmp
sops:
    age:
        - recipient: age1fcyhrk0yse8cx49cq398z2uaewp3vxzqek5uph0usgsthzvspppqjp7dru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuRWp0b2tlQ3kwL1pxRjcz
            MG1KZ2U5ZDRVSGVJc3VYRXZXdWdLc1ZmVlc0CmE1NTMrUTQ1dmlkOGRteFN3bHZO
            aW8vbnJEcHJPdUVkOHFlOGkvU21KTHMKLS0tIHE1RlBYZ2QrRWIzMENwMHI1OWVp
            M1BlTVBDclVDM0oyTHh5MjVwTDJVcFEKTjNBCBcqZ85X0YRLaz9Yr9Q8ViovhLL9
            a0pmRkzI1BcIDiXG/5JnVag+rX5414r7DaTW7kXDjzI3NzPhPcMKTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T16:29:03Z"
    mac: ENC[AES256_GCM,data:BZFbOQpUA6lmc1zfRTVDV5z8jOaV9VWtFUIaaeYqppL8JwOKD84zaZnlQksrjcGutOJYbZMHYt0IKa42DwjFlRRrDt/O9fPznoq/HLKWTigcE5Qm/gFMJXFdRAvmtO2kAxc1dopFtxH+ZdpHRG40N/6JHROLMY6VGBaq5HelihA=,iv:5PuJjV61R4pEK2lDVC4rYldshi8TpohNeUcfqaF+Nn8=,tag:D0SxlUfglS65T/jbeJ47Rw==,type:str]
    encrypted_regex: ^[A-Z0-9_]+__APIKEY$
    version: 3.10.2
