apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: slskd
    namespace: servarr
spec:
    interval: 30m
    chart:
        spec:
            chart: app-template
            sourceRef:
                kind: HelmRepository
                name: bjw-s
                namespace: servarr
    upgrade:
        cleanupOnFail: true
    values:
        controllers:
            slskd:
                type: deployment
                pod:
                    securityContext:
                        runAsUser: 1000
                        runAsGroup: 65533
                        fsGroup: 65533
                        fsGroupChangePolicy: OnRootMismatch
                containers:
                    app:
                        image:
                            repository: slskd/slskd
                            tag: latest
                            pullPolicy: IfNotPresent
                        env:
                            TZ: Europe/Rome
                            UMASK: "002"
                            SLSKD_REMOTE_CONFIGURATION: true
                            SLSKD_DOWNLOADS_DIR: /media/Downloads
                            SLSKD_INCOMPLETE_DIR: /media/IncompleteDownloads
                            SLSKD_SHARED_DIR: /media/Music
                            SLSKD_USERNAME: fonzdm
                            SLSKD_PASSWORD: ENC[AES256_GCM,data:OhamfJau4bQ=,iv:zaL2gl1KoNpKxmzf42X1mpznuMmTk3eiJE377u+Wrf0=,tag:MFEH8Arwee2ModXJsw0LeQ==,type:str]
                            SLSKD_SLSK_USERNAME: fonzdm-slsk-user
                            SLSKD_SLSK_PASSWORD: ENC[AES256_GCM,data:2TnpRSMC/vk95kNt7u8JnQ==,iv:oKbMeWYR71aob5eSuttNzBw0IqmjKzAmrVzp3Vbmkeo=,tag:DsKGArK6hvva4GCmmmLGrw==,type:str]
                            SLSKD_CONTROLLER_API_KEY: ENC[AES256_GCM,data:K6chKXYuCqMu7TWMnrtMiOqcFTTyX+RMEercntEvEa+CfG4srnzOxo7TBNYFR2+JLC/wvYNVhC5fNcsh/YZuWA==,iv:AeSqnEr01ASgAQ5CyoYraBNxkzDpxUQdxN/tUKlVgsY=,tag:mmQDrcgPqVxjNYVP2L5m3Q==,type:str]
                        ports:
                            - name: http
                              containerPort: 5030
                            - name: soulseek
                              containerPort: 50300
                        probes:
                            liveness:
                                enabled: true
                                spec:
                                    periodSeconds: 30
                                    timeoutSeconds: 5
                                    failureThreshold: 5
                            readiness:
                                enabled: true
                            startup:
                                enabled: true
                                spec:
                                    failureThreshold: 30
                                    periodSeconds: 10
        service:
            app:
                controller: slskd
                ports:
                    http:
                        port: 5030
                    soulseek:
                        port: 50300
        ingress:
            main:
                enabled: false
                # enable later if you expose through traefik/nginx
        persistence:
            config:
                enabled: true
                type: persistentVolumeClaim
                accessMode: ReadWriteOnce
                size: 2Gi
                globalMounts:
                    - path: /app
            media:
                enabled: true
                existingClaim: talos-media-volume
                globalMounts:
                    - path: /media
        resources:
            requests:
                cpu: 50m
                memory: 256Mi
            limits:
                memory: 1Gi
sops:
    age:
        - recipient: age1fcyhrk0yse8cx49cq398z2uaewp3vxzqek5uph0usgsthzvspppqjp7dru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWb09IUUpuQTJxRHR3bnFE
            Vk8vT0FadmlFZTUvN3FUcnp1ekFCV2ZuUnowClRWaFc2RUhWc0xuSzBKeGFwNjhM
            L3Ewd2NjaUVnYVJxcVNPN0hQb0g4Q1kKLS0tIHBxY21LVHFwd1ErbWovdEpodnhX
            cWtuckJlbDVFanVkYWZxb2EzRlA0c3cKWV19YSLM6XJgtA7enfCjHhP9F0oN4y5T
            QY3cNciWQ41pkQzR/IyEGcyqsNSL1gdfpU1S/0j7XWS//RU46fQNeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T08:35:49Z"
    mac: ENC[AES256_GCM,data:kyGNTbV53QouIRB1XVLOCa7BUEQbE7RTY+cij9n5w2Z2oDvw6qkalt2x7MKzyWNOwilnKpRf3+71xavud764pZFGmF5hUUKkLFpCH0UgcIiST+CwNmdEyFsrTPchbtTeDwRCZ5yFaP9zklKB0q4GGK7+rs4WlpJ9V6CV/ZWIu6c=,iv:YLQo1KddCYVUHHOZVxj3hiCQuho73B/tVJRqhfXY0Ts=,tag:CHnrL6xaD+inSatnzLxeYQ==,type:str]
    encrypted_regex: ^(?:SLSKD(?:_SLSK)?_PASSWORD|SLSKD_CONTROLLER_API_KEY)$
    version: 3.10.2
