apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: slskd
  namespace: servarr
spec:
  interval: 30m

  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: servarr

  upgrade:
    cleanupOnFail: true

  values:

    controllers:
      slskd:
        type: deployment
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 65533
            fsGroup: 65533
            fsGroupChangePolicy: OnRootMismatch
        containers:
          app:
            image:
              repository: slskd/slskd
              tag: latest
              pullPolicy: IfNotPresent

            env:
              TZ: Europe/Rome
              UMASK: "002"

            ports:
              - name: http
                containerPort: 5030
              - name: soulseek
                containerPort: 50300

            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true

    service:
      app:
        controller: slskd
        ports:
          http:
            port: 5030
          soulseek:
            port: 50300

    ingress:
      main:
        enabled: false
        # enable later if you expose through traefik/nginx

    persistence:

      config:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 2Gi
        globalMounts:
          - path: /app

      media:
        enabled: true
        existingClaim: talos-media-volume
        globalMounts:
          - path: /media

    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        memory: 1Gi