apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: sonarr
    namespace: servarr
spec:
    interval: 1h0m0s
    chart:
        spec:
            chart: app-template
            sourceRef:
                kind: HelmRepository
                name: app-template
    values:
        controllers:
            sonarr:
                annotations:
                    reloader.stakater.com/auto: "true"
                pod:
                    securityContext:
                        fsGroup: 2000
                        fsGroupChangePolicy: OnRootMismatch
                        runAsGroup: 2000
                        runAsNonRoot: true
                        runAsUser: 2000
                containers:
                    app:
                        image:
                            repository: ghcr.io/home-operations/sonarr
                        env:
                            SONARR__APP__INSTANCENAME: Sonarr
                            SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:ttgBt3mPSdGZUxOkbz1Crtr+V1JkbzZzdv5t2j6Hkvp8,iv:H8sBU8+PuAmIVtTEe2AXK8cV372Vo5VuRj2WqmnH2L4=,tag:T5X0EsFnoitP+ubsd4OEPQ==,type:str]
                            SONARR__AUTH__METHOD: External
                            SONARR__AUTH__REQUIRED: DisabledForLocalAddresses
                            SONARR__LOG__DBENABLED: "False"
                            SONARR__LOG__LEVEL: info
                            SONARR__SERVER__PORT: 8989
                            SONARR__UPDATE__BRANCH: develop
                        probes:
                            liveness:
                                enabled: true
                                spec:
                                    periodSeconds: 30
                                    timeoutSeconds: 5
                                    failureThreshold: 5
                            readiness:
                                enabled: true
                                custom: true
                                spec:
                                    httpGet:
                                        path: /ping
                                        port: 8989
                                    periodSeconds: 10
                                    timeoutSeconds: 5
                                    failureThreshold: 5
                            startup:
                                enabled: true
                                spec:
                                    failureThreshold: 30
                                    periodSeconds: 10
                        resources:
                            requests:
                                cpu: 20m
                                memory: 384Mi
                            limits:
                                memory: 2Gi
                        securityContext:
                            allowPrivilegeEscalation: false
                            readOnlyRootFilesystem: true
                            capabilities:
                                drop:
                                    - ALL
        service:
            app:
                ports:
                    http:
                        port: 8989
        persistence:
            media:
                existingClaim: talos-media-volume
            tmpfs:
                type: emptyDir
                globalMounts:
                    - path: /tmp
                      subPath: tmp
sops:
    age:
        - recipient: age1fcyhrk0yse8cx49cq398z2uaewp3vxzqek5uph0usgsthzvspppqjp7dru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLU25NK3I5YXFYb0hQeEM1
            UFZkajhqL3A4Q2NVV2xZTHNnekY3eHVocENNCndhOGt4OXlEWmROYVVOUy9CZHlV
            SzVHV2srUEVtYXp3VER0dUwrMXNmNTgKLS0tIHROZitNVXMwTnpRWDN6NXB5MTVn
            Z0RReUlNc0hkRkp1RFUvVDFLYmxXeFkKF9nDDyxeH040FN3EHL9kxlh36Ig9rKYh
            R/pP6APVYnUbu86ErcI9a+iCyzSg9TE44x1KxlvMsztHe4vTrVvBkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T16:29:09Z"
    mac: ENC[AES256_GCM,data:yEG2jX58ucXdPE6MOmvPMjPxRfBX/6JmRm2XZsuyxFZArDxT+uM3HyGIlF3oPMc/JcHG8xvq4Y/3HibeSzWIchJ7RQY0byx8fVDnbvjaVlr2WKw0fXuoONv3RGoH3PmHqZa4AeBRDRSL4ymYxnH4QeD8skw0Crs/0ajqggXF2DU=,iv:+/+5TlIsdKPCFInjMBJl6h22+LWX0pUTVWF7quK3WB4=,tag:mx8jgrdjr2Fd0Pu3G9il+Q==,type:str]
    encrypted_regex: ^[A-Z0-9_]+__APIKEY$
    version: 3.10.2
