apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:4vweBqWSXgZvKJcM8kAYM4A=,iv:TAL7Hrv/Vn/PRxuepH/v1dJ0im0A+9nh01TWndG7JAY=,tag:rsS+zNHVE01A7VR52I71VQ==,type:str]
    client_secret: ENC[AES256_GCM,data:P4MT8ahfznIvm90b9w/ljPnMtffU5UZuAoPLLZ3WFspVP+GxDNtLycUji/pZqXgfrWZALJkBrOOTuO7Edgmqsg==,iv:PvpirPVp6VBThuz+BleLSQp28iF9VUyfF0FDNRW1ARk=,tag:4LSk23kUaVsJqFnpmJAedg==,type:str]
sops:
    age:
        - recipient: age1fcyhrk0yse8cx49cq398z2uaewp3vxzqek5uph0usgsthzvspppqjp7dru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpUEs3cFk5ZTNuMjRjUitE
            M2VYOU55WTBEbkw5R2NRYm9wMk9rTlUxQlM4CnpmN3dFeXpTUlNvZWdrb1BBSzdN
            TlhnSkhmaTRVRnJoL1VwUWl3QWJFZUUKLS0tIGNQOFhKV0hmV0hTVUxDcGFyNzFI
            YXBLTnBPVjZwMVAzWk5wbDQwQXZ1NW8KdQtyIly5FDR4WXjAZyxGRr3FHjC4VziA
            BOYDuI9ZTjNU+6W3gUwdMzYpOTgVyqlM4GeqweK3R7lcsEf3jLnYXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-27T21:58:22Z"
    mac: ENC[AES256_GCM,data:TJ1Bj2oVODhRJrNYvYnukkM/KnBVcNdxt7DmTKEGnd8eT32r+6P5q3j5SGIn3krYDgspWdpW3Ly4/HPDncotzXI8AQUDbAz2WukDqJmsN0jm9z9m+58/AlOvW3zTlsvM+ZwzYNtz6kpLY9nygSIsLhVdv8R4wFxfKiGQ9QYZ0MQ=,iv:1CPHqI31eCDXuyCIINJGX1CB0ZDdPpg7j7Xzrv3oQw4=,tag:O7ANN+jpx7z87srMzNWBcg==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.10.2
