apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-m 
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - issuer.yaml
  - ca-certificate.yaml
  - ca-issuer.yaml
  - root-cluster-issuer.yaml

