apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: servarr
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: jellyfin
      sourceRef:
        kind: HelmRepository
        name: jellyfin-charts
  values:
    replicaCount: 1
    image:
      pullPolicy: IfNotPresent
    persistence:
      config:
        enabled: true
        size: 8Gi
        storageClass: 'localpv-raid'
      media:
        enabled: true
        existingClaim: talos-media-volume
    ingress:
      enabled: true
      className: 'traefik'
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-cloudflare
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.middlewares: default-jellyfin-buffering@kubernetescrd
      hosts:
        - host: jellyfin.media.fonzdm.xyz
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: jellyfin-tls
          hosts:
            - jellyfin.media.fonzdm.xyz
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
