apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: servarr 
resources:
  - resources/talos-media-volume.yaml
  #- resources/servarr-ing-external.yaml
  # - regcred.yaml 
  - resources/repository.yaml
  - components/qbittorrent-operator.yaml
  - components/lidarr.yaml
  # - components/radarr.yaml
  - components/sonarr.yaml
  - components/slskd.yaml
  - components/jellyfin.yaml
  # - components/audiobookshelf.yaml
  # - components/prowlarr.yaml
  # - components/flaresolverr.yaml
  # - components/jellyseerr.yaml
  # - components/bazarr.yaml
