apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: servarr 
resources:
  - qbittorrent-credentials-secret.yaml
  - torrent-config.yaml
  - jellyfin-traefik.yaml
  - qbittorrent-traefik.yaml
  - sonarr-traefik.yaml
  - lidarr-traefik.yaml
  - slskd-traefik.yaml
  - prowlarr-traefik.yaml
