apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-credentials
    namespace: servarr
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:6xa7Y59F,iv:eF6ch/cxXFQ+TdOiqlk3/axYGNT9uOkn/yNssJwrUUw=,tag:TRrah7FPY8ndvkdFp/KJIA==,type:str]
    password: ENC[AES256_GCM,data:nfdvCNh5yBJu,iv:muAT7/ugiI59DdFdde8ulErruP0nyMNBxGKPUisAWr4=,tag:JTPltj/zuyqszE1OfYL1Pw==,type:str]
sops:
    age:
        - recipient: age1fcyhrk0yse8cx49cq398z2uaewp3vxzqek5uph0usgsthzvspppqjp7dru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6S3hZQ3BWL29VWitWK0lD
            RjNjRXI1eWplbzk2T3BjcjZ4Q291U25tK1RjClo2WDRqbW52RkduaHFhK09tdkFv
            bWpxZ0dVVHZUNXBKZnZJRHJrd1VKNjgKLS0tIDhrMUQrVk8zdGNESEFZeDBqUWhK
            aVordWZwaWNZVTdydFQvcE03akt1dXMKM2uSVGtjGAgfi+iYikUneAqQVj9Q04ji
            cruxGePgUtF3ndgVETgd5qZdEY+aYO/n71E8I5xVD2lR+82uOGT1pQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T08:56:48Z"
    mac: ENC[AES256_GCM,data:LiIoEW/lXuGrMguJts6TljoUxsA9014zBqvPUjXR/f+PMtPEqIVSAEOvHZZj8NrT8aoqjBuNtyOxFFYAs6HwbptyrF+yPMxQZmVJzJ0twGzjY+X+5RJlJBXTPFSZ99X3JOotXeGg6W34ZeKSorHalGmS05gn8MbfRGVrL+HKa4c=,iv:NFlHvUpda9bMtewxQauV3FdvUpeb4q6qQCIXgBbWKB8=,tag:FUz59CQA/XTQefGhqZgyYw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
