apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nas-main
  namespace: nas 
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: democratic-csi
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
  valuesFrom:
    - kind: Secret 
      name: release-main-values
      valuesKey: values.yaml

