apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nas
  namespace: nas 
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: democratic-csi
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
      version: 0.14.7
  valuesFrom:
    - kind: Secret 
      name: release-values
      valuesKey: values.yaml
