apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: actions-runner-controller
spec:
  interval: 10m
  url: https://actions-runner-controller.github.io/actions-runner-controller
  type: default
