apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: theia-cloud-base 
spec:
  interval: 10m
  releaseName: theia-cloud-base
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: theia-cloud-base
      sourceRef:
        kind: HelmRepository
        name: theia-cloud
        namespace: theia-cloud
      interval: 30m
  valuesFrom:
    - kind: Secret
      name: theia-cloud-base-values
      valuesKey: values.yaml

---


apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: theia-cloud-crds 
spec:
  interval: 10m
  releaseName: theia-cloud-crds
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: theia-cloud-crds
      sourceRef:
        kind: HelmRepository
        name: theia-cloud
        namespace: theia-cloud
      interval: 30m
  valuesFrom:
    - kind: Secret
      name: theia-cloud-crds-values
      valuesKey: values.yaml

---


apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: theia-cloud
spec:
  interval: 10m
  releaseName: theia-cloud
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: theia-cloud
      sourceRef:
        kind: HelmRepository
        name: theia-cloud
        namespace: theia-cloud
      interval: 30m
  valuesFrom:
    - kind: Secret
      name: theia-cloud-values
      valuesKey: values.yaml
