apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.io/ip-allocated-from-pool: external-pool
    metallb.io/loadBalancerIPs: 192.168.100.5
    metallb.io/allow-shared-ip: external-pool
  name: ingress-nginx-controller-2
  namespace: ingress-nginx
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Local
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - appProtocol: http
    name: http2
    port: 8080
    protocol: TCP
    targetPort: http
  - appProtocol: https
    name: https2
    port: 8888
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
  sessionAffinity: None
  type: LoadBalancer

