apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: overall-image-updater
  namespace: flux-system
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: alfixdemasi@gmail.com
        name: fonzdm
      messageTemplate: '{{range .Changed.Changes}}{{print .OldValue}} -> {{println .NewValue}}{{end}}'
    push:
      branch: main
  update:
    path: ./kubernetes/talos
    strategy: Setters

---

apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: lidarr-imagerepo
  namespace: flux-system
spec:
  image: ghcr.io/home-operations/lidarr
  interval: 5m

---

apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: lidarr-imagepolicy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: lidarr-imagerepo
  filterTags:
    pattern: '^rolling$'
  policy:
    alphabetical: {}
  digestReflectionPolicy: Always
  interval: 10m